### ISSUE TITLE
Customize route failure response

### ISSUE THREAD

**Issue by aturon** [rust-net-web/tide#10]
Right now, Tide always returns an empty 404 response when there is no route match. This should be customizable.

Possibly blocked by https://github.com/rust-net-web/tide/issues/5, if we want to use the same configuration mechanism for this.

**Comment by aturon** [comment]
Also note that currently no middleware is applied to this fallback 404 responder. Worth thinking if that's what we want.

**Comment by tzilist** [comment]
@aturon Currently working on this. Thought process is as follows:

We can allow user's to specify a default handler. This function will run if no route match is found. The other thing i'd like to implement is an error handler akin to actix-web's, [see here](https://github.com/actix/actix-web/blob/master/src/middleware/errhandlers.rs#L33). I think between the two of them, that should give a pretty good start for  handling any kind of failures that can happen during a request :) Let me know what you think!
