### ISSUE TITLE
The links to `Code of Conduct` are broken in `Contributing.md`

### ISSUE THREAD

**Issue by HeroicKatora** [rust-net-web/tide#127]
The links in [Contributing.md](https://github.com/rust-net-web/tide/blob/9da9a1ed0ad00c762168c909a9400b25197e78ca/.github/CONTRIBUTING.md) do not render the interactive links to the code of conduct. Instead, the document contains the links in `[]` blocks that don't render on github. These should be changed to `[Code of Conduct](./CODE_OF_CONDUCT.md)`

**Comment by yoshuawuyts** [comment]
@HeroicKatora would you be interested in writing a patch for this?

**Comment by HeroicKatora** [comment]
@yoshuawuyts Ping, see the pull request that fixes this.
