### ISSUE TITLE
Support named path extraction

### ISSUE THREAD

**Issue by aturon** [rust-net-web/tide#13]
The router supports both named (`{foo}`) and anonymous (`{}`) wildcards, but Tide only has an extractor (`Path`) for the latter.

However, extractors are given `RouteMatch` structures which contain named match information.

All that's needed is to add an additional extractor type for extracting path components by name. Here's a sketch:

```rust
trait NamedComponent: Send + 'static + std::str::FromStr {
    const NAME: &'static str;
}

struct Named<T: NamedComponent>(pub T);

impl<T: NamedComponent, S: 'static> Extract<S> for Named<T> { ... }
```

**Comment by mythmon** [comment]
With #32 merged, should this issue be closed, or is there more work to do?

**Comment by tirr-c** [comment]
I think this is good to close.
