### ISSUE TITLE
Pin nightly version foir CI

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-net-web/tide#134]
It's hard to consistently develop against tide, as Clippy on nightly now more often seems to fail than to pass. I think if we could pin the nightly version (at least for now), we could make developing Tide itself a bit more straight forward.

**Comment by aturon** [comment]
Agreed! I... think there may be some way to do this with rustup. cc @alexcrichton

**Comment by yoshuawuyts** [comment]
@aturon I hard-coded a pinned version in `.travis.yml` which effectively solves the problem. I'd be curious to know if there might be any, err, more polished solutions.

**Comment by alexcrichton** [comment]
To get a guaranteed version of clippy the recommendation is "either beta, stable, or a pinned nightly", and unfortunately we don't have much tooling beyond that :(
