### ISSUE TITLE
Document routing syntax

### ISSUE THREAD

**Issue by aturon** [rust-net-web/tide#18]
The `at` method should be documented with the router syntax and fallback semantics.

**Comment by hseeberger** [comment]
I think I'd like to give it a shot, because I'm a Rust and Tide newbie and hence a documentation task seems a good entry point.

I'm not quite sure though what kind of documentation to create – I guess we are talking about documentation comments (`///`), right?

**Comment by tirr-c** [comment]
I see this is resolved now, is it okay to close?

**Comment by hseeberger** [comment]
Thanks. Yes, for me that's fine.
