### ISSUE TITLE
Always-applied middleware

### ISSUE THREAD

**Issue by tirr-c** [rust-net-web/tide#61]
Currently Tide won't run any middleware if the routing fails. We might want to change this, as some middleware should run regardless of the routing result, such as logging or compression.

The easiest way I can think of is:
* Only apply middleware of the top-level router.
* Run a chain of middleware with empty `RouteMatch`. Alternatively, we can make `RouteMatch` optional to indicate the routing has failed.

**Comment by tirr-c** [comment]
One step further: we might be able to turn routing logic into middleware, and let the middleware chain do the work. The problem is that the routing will generally be the last step of top-level middleware application. That means, the other top-level middleware won't have access to `RouteMatch`.

**Comment by aturon** [comment]
Personally, I'm a bit wary of trying to move routing fully into middleware -- it's a very clever idea, but in my experience these kinds of extreme unifications often end up hurting more than they help.

I think the proposal in the original post sounds good, and I like the idea of having `RouteMatch` clearly signal that no match occurred by using `Option`.

**Comment by tirr-c** [comment]
This is resolved by #64! Closing this issue.
