### ISSUE TITLE
Use the same port in the examples

### ISSUE THREAD

**Issue by ibaryshnikov** [rust-net-web/tide#78]
Some examples contain
```
app.serve("127.0.0.1:8000");
```
And others are
```
app.serve("127.0.0.1:7878")
```
Can we have the same port for all of the examples?
Also, is it a good idea to print the url? Like

**Server is listening on http://127.0.0.1:8000**

to be able to navigate to the browser by click

**Comment by aturon** [comment]
Closed by #79
