### ISSUE TITLE
Consider renaming `App::at()` to `App::path()`

### ISSUE THREAD

**Issue by kud1ing** [rust-net-web/tide#96]
I propose to rename `App::at()` to `App::path()`.

`at()` is short and thus easy to type, but it bears not much context.

I think

    app.path("/").get(index_endpoint)

would be slightly more descriptive/readable than

    app.at("/").get(index_endpoint)

**Comment by yoshuawuyts** [comment]
It seems most of the discussion around this is currently happening on the PR #103.
